---
title: "Stegen 03 Univariate and stratified analysis"
author: "Janetta E. Skarp"
date: "4 October 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Univariate analysis

# Question 2:  What is/are the vehicle/s for this outbreak?
### a) Compute food-specific attack rates and % of cases exposed
### b) Choose the appropriate measure of association and the appropriate statistical tests and appropriate level of confidence 
### c) Look at the proportion of cases exposed. What would be your suspected food item at this point?
### d) Compute the proportion of cases exposed for each exposure
### e) Search for any dose response if appropriate
Consider whether you would recode this variable so it has fewer categories, and actually do it.
**Hint** Use the variable tportion and tabulate it. 
### f) Interpret the results and identify the outbreak vehicle if any.

# Hints for question 2
As we are carrying out a cohort study, the appropriate measure of association is relative risk. The appropriate statistical test for determining a p-value is a Chi-squared test of comparison of proportions. For our analyses we will use a 95% confidence level, as this is the standard used in public health.

# Stratified analysis

# Question 3:  Assess whether the chocolate mousses were the vehicles of the illness.
**Hint** Think about effect modification and confounding.

# Question 4. Assess whether beer had a protective effect on the occurrence of illness.

What would you do next?